### ISSUE TITLE
material-ui-icons is deprecated. Use @material-ui/icons

### ISSUE THREAD

**Issue by o-m-a-r-k** [techniq/mui-downshift#25]
https://github.com/techniq/mui-downshift/blob/baaa17667f3b533165d6e8efd456ecadc449e79f/src/Input.js#L7
https://github.com/techniq/mui-downshift/blob/baaa17667f3b533165d6e8efd456ecadc449e79f/src/Input.js#L8

**Comment by smlynch** [comment]
Updated in `1.0.0-12`  (`yarn install mui-downshift@next`).  Thanks
