### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by stefanwille** [techniq/mui-downshift#26]
Hi Sean,

this project looks very useful, thanks!

It was not obvious to me what the license is for this project. After searching the code, I found the license field in package.json says it's MIT licensed. Is this correct?

It would be great to have a LICENSE file like Downshift: https://raw.githubusercontent.com/paypal/downshift/master/LICENSE

Ciao :-)

**Comment by smlynch** [comment]
@stefanwille thanks, and good catch.  I've added the LICENSE file.
