### ISSUE TITLE
Update with Current material-ui@next directory structure

### ISSUE THREAD

**Issue by najisawas** [techniq/mui-downshift#31]
I just installed via `yarn add mui-downshift` and it seems like the package is out of date with material-ui's current directory structure.

I'm getting a compilation error that says it cannot resolve from `material-ui/LinearProgress` because `material-ui` now imports `{ LinearProgress }` from `material-ui/Progress`

https://material-ui-next.com/demos/progress/

I'm not sure what other things are out of date as this is the only issue I've come across without tweaking the node_module myself

**Comment by techniq** [comment]
@najisawas You need to install `mui-downshift@next` as I haven't release a non-prerelease for material-ui-next yet.  Let me know if that fixes it for you.

I plan to wait until Material-UI 1.0 is officially released ([May 17th](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.45)) and after I get time to implement mutli-select (#5) before I release mui-downshift@1.0

**Comment by goyney** [comment]
Using "next" of this library doesn't work with the latest @material-ui/core which is at 1.0.0.
