### ISSUE TITLE
Setting % based width, not working

### ISSUE THREAD

**Issue by serle** [techniq/mui-downshift#35]
I am unable to set the width if it is a percentage based width, using getRootProps(). Looking at the code, the popper Manager seems to be the actual root of the component.

**Comment by techniq** [comment]
Hmm, currently the [Input](https://github.com/techniq/mui-downshift/blob/master/src/Input.js#L40) is set to fullWidth (sets `width=100%` via Material-UI styling) and I just put the component into a parent with the styling set to the desired width (for example, within a [Grid](https://material-ui.com/layout/grid/) component)

Could this work in your case?
