### ISSUE TITLE
Feature Request: Ability to style InputAdornment

### ISSUE THREAD

**Issue by serle** [techniq/mui-downshift#36]
Currently the InputAdornment is way oversized. Could you provide a ability to pass through a classes structure on the component and propagate a class onto your InputAdornment and IconButton.

**Comment by techniq** [comment]
See this [PR](https://github.com/techniq/mui-downshift/pull/33#issuecomment-396627468) where it was discussed on to do this currently (overriding `endAdornment` so you can then style the underlying components.

I admit we need a better customization/override story here.  It's difficult as using `endAdornment` for clear and dropdown button, but also supporting custom actions here (I've added a "copy to clipboard" button here as well in some of my projects).

I'm open for exposing `classes` like other Material-UI components to give you some styling options for the existing components.  Also need to come up with a good solution for custom adornments or overriding the existing ones beyond styling (changing the icon component, etc)

**Comment by cvanem** [comment]
@techniq Any progress on this?  I prefer smaller adornments and the clear icon to be at the end like this:
![image](https://user-images.githubusercontent.com/24579103/52907803-260c5800-3226-11e9-916f-bf059d591c62.png)

The touchable icon widths end up being 24x24 px but I think it looks much better and still seems usable.

What if we were to add a renderEndAdornment callback to accomplish the customizations you described above?  Only overriding classes, could be useful but it doesn't allow for more advanced customizations.   Is it worth creating a PR for this?

**Comment by techniq** [comment]
After merging @cvanem's PR, this is now resolved.   At some point I plan to restructure accessing downshift props (and other handlers, etc) via React context or hooks (or maybe both... `React.useContext(DownshiftContext)`) but pushing more things down into `getInputProps` works for now.
