### ISSUE TITLE
Menu items outside of initial viewport aren't clickable

### ISSUE THREAD

**Issue by wingfield4** [techniq/mui-downshift#4]
Items in the drop down menu are clickable only if they are in the initial viewport, plus one or two. If you scroll down and click on a item, nothing happens

**Comment by techniq** [comment]
Even though setting `scrollToIndex` to `0` when `highlightedIndex` is null [works](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=windowing%20with%20react-virtualized&full=0&down=1&left=1&panelRight=0) in the [example](https://github.com/paypal/downshift/blob/master/stories/examples/windowing-with-react-virtualized.js#L48)...
```js
<VirtualList
  scrollToIndex={highlightedIndex || 0}
  ...
/>
```
...I needed to not set `scrollToIndex`if `highlightedIndex` was null to fix this issue
```js
<VirtualList
  { ...highlightedIndex != null && { scrollToIndex: highlightedIndex}}
  ...
/>
```
