### ISSUE TITLE
set value after populating items

### ISSUE THREAD

**Issue by PatrickSannes** [techniq/mui-downshift#40]
I have a dropdown that I want to use in an editform. Is it possible to select an item from the provided items. I would expect somthing like:
```
  <MuiDownshift
      items={filteredOptions}
      value={this.props.value}>
 </MuiDownshift> 
```

**Comment by techniq** [comment]
You can initialize it using [defaultSelectedItem](https://github.com/paypal/downshift#defaultselecteditem) or control it using [selectedItem](https://github.com/paypal/downshift#selecteditem)
