### ISSUE TITLE
npm/yarn still think 0.0.19 is the newest version

### ISSUE THREAD

**Issue by hukka** [techniq/mui-downshift#42]
https://www.npmjs.com/package/mui-downshift shows how the current version, 1.0.0-19, is considered to be pre-release and is not considered to be newest. Concretely, simply trying `yarn add mui-downshift` will get that months old version.

**Comment by techniq** [comment]
@hukka I had been holding out releasing `1.0.0` officially until I was sure I could handle #5 without any breaking changes.  I was pretty sure an API changes wasn't going to be needed after experimenting a little on the [multi-select](https://github.com/techniq/mui-downshift/commit/9fffea2e0a342f7dcd228de4ee248af86924e32f) branch but I just haven't had the time to create the examples I was hoping to.  I was also waiting for Material-UI 1.0.0 to officially be released, which it has for a while now.

With that said, I decided it was time to release `1.0.0` officially  🎉 and I can always cut a 2.0.0 release if the API does need to change.
