### ISSUE TITLE
Please consider removing the FormControl's hardcoded 'fullWidth' property

### ISSUE THREAD

**Issue by SladeRun14** [techniq/mui-downshift#47]
We would like to suggest that you consider -- in the event that you haven't already -- the assumption that all mui-downshift components will want to span the entire width of their parent container.

With reference to the attached images, please note that we position our input controls in pairs within a single MUI `<Grid item>` container.  

![good](https://user-images.githubusercontent.com/14039556/43911199-e0318fca-9bcc-11e8-9d53-b64c3220f0bf.png)

So the "City" control and the mui-downshift "State/Province" select control are in the same container. To achieve the proper side-by-side placement we must remove the 'fullWidth' property hardcoded into the FormControl at
Line 43 of Input.js file (`<FormControl disabled={disabled} required={required} error={error} fullWidth>`) 

Here's what the form looks like before we remove that property:
![bad](https://user-images.githubusercontent.com/14039556/43911480-921ede18-9bcd-11e8-84ef-2faa50140306.png)

The mui-downshift control thinks it should span the entire `<Grid item>` container, which has the effect of pushing it to the next line.

Thanks for reading and if we've missed or misused some aspect of your fine work, please let us know.

**Comment by techniq** [comment]
@SladeRun14 thanks for the feedback.  I've thought about this before, and it would be a breaking change (would result in a `2.0.0` release).  I like to keep things as little opinionated as possible, and I think removing the `fullWidth` would fall within that.

I would still like to ability to opt-in for those use cases (I typically turn it on for all my inputs).  Problem is what to call it.  We already have `getInputProps` that gets applied to the `MuiInput` component.  Possibly `getFormControlProps`.

https://github.com/techniq/mui-downshift/blob/master/src/Input.js#L43

I'm not sure when I'll be able to get to this, but if you could send a PR that I could review, I might be able to get that done quicker (shouldn't be a huge overall change, but would need 1 o 2 storybook stories added, etc).

**Comment by SladeRun14** [comment]
@techniq thanks for considering our comment.  It looks like mui-downshift is not suitable for our use case.  Simply removing the `fullWidth` property wasn't enough to achieve the positioning we desire.  We also had to hardcode an MUI className in the outermost div:  `<div className="MuiFormControl-root-251" {...getRootProps && getRootProps()}>` which is a bit of a smell.  And even then the mui-downshift component doesn't position itself correctly on initial display.  The page has to be refreshed for the component to pop into place.  

Should we discover an acceptable mui-downshift mod as we re-evaluate our options, we'll consider sending a PR. In the meantime, thanks again for your contributions to the material-ui space.
