### ISSUE TITLE
Storybook not starting

### ISSUE THREAD

**Issue by Sm00g15** [techniq/mui-downshift#66]
```
/bin/sh: start-storybook: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
is the error I get when I run yarn storybook

**Comment by techniq** [comment]
Hmm... works here :)

I assume you've ran `yarn install` first?  Also, run `ls -l node_modules/.bin/start-storybook` to verify the executable is available.

![image](https://user-images.githubusercontent.com/177476/48917632-ce906300-ee55-11e8-946b-aeef218041fd.png)

**Comment by Sm00g15** [comment]
yarn upgrade did the trick for me

**Comment by ryb73** [comment]
This happened to me after doing a `yarn upgrade-interactive` and running `yarn` afterwards fixed it for me
