### ISSUE TITLE
Controlled component

### ISSUE THREAD

**Issue by jgoux** [techniq/mui-downshift#7]
Hello,

it seems that making MuiDownshift a controlled component is impossible right now.

I think you need to pass the `selectedItem` prop to `Downshift`.

**Comment by techniq** [comment]
Seems reasonable, and I kind of thought we already had that.  I don't assume it will break anything currently passing in `selectedItem` would be my only concern (but it's probably OK).  We should just need to explicitly pass it [here](https://github.com/techniq/mui-downshift/blob/master/src/index.js#L67).

Could you submit a PR?

**Comment by jonyonson** [comment]
What o
