### ISSUE TITLE
Can't resolve 'prop-types'

### ISSUE THREAD

**Issue by shilangyu** [techniq/mui-downshift#70]
Getting the following error:
`Module not found: Can't resolve 'prop-types'`.
Yes I do not use prop-types, yes installing the package manually fixes the problem.
My point is that I dont think mui-downshift should assume users will have prop-types installed.

**Comment by techniq** [comment]
@shilangyu Could you send a PR to add it?

**Comment by shilangyu** [comment]
@techniq sure, as a peer or normal dependency?

**Comment by techniq** [comment]
Normal dependency would be fine (that's how [downshift](https://github.com/downshift-js/downshift/blob/master/package.json#L71) does it and would handle it more transparently for a user)

**Comment by techniq** [comment]
Thanks for the PR.  Released as part of `1.2.3`
