### ISSUE TITLE
Set value manually

### ISSUE THREAD

**Issue by shilangyu** [techniq/mui-downshift#79]
How do I set the current value programmatically? I want to create a default value during render.

**Comment by shilangyu** [comment]
Should've done much more research before posting, stories' code helped a lot:
```jsx
<MuiDownshift
  getInputProps={() => ({
     value: 'default value'
  })}
  items={filteredItems}
  inputRef={node => {
    this.input = node
  }}
/>
```

**Comment by shilangyu** [comment]
The above method works only visually, mui-downshift doesnt see the value. Reopening.

**Comment by cvanem** [comment]
As this is a wrapper over downshift, I think you need to pass in the actual [downshift props](https://github.com/downshift-js/downshift) to set the initial value or selected value.  

See [initialSelectedItem ](https://github.com/downshift-js/downshift#initialselecteditem) and [initialInputValue](initialInputValue)

**Comment by shilangyu** [comment]
@cvanem
thank you for your reply. I tried both and couldnt get them to work:
```jsx
<MuiDownshift
  initialInputValue={'default value'}
  items={filteredItems}
  inputRef={node => {
    this.input = node
  }}
/>
```
```jsx
<MuiDownshift
  initialSelectedItem={'default value'}
  items={filteredItems}
  inputRef={node => {
    this.input = node
  }}
/>
```

**Comment by cvanem** [comment]
@shilangyu It doesn't appear to be working for me either.  
It looks like this package may be using an older version of downshift.  See [old documentation](https://github.com/downshift-js/downshift/blob/3fb0ed21278c5f1d0a077ed9b1d0dfd55a75c71b/README.md#defaultselecteditem).

**Comment by cvanem** [comment]
@techniq Is it time to update this library to downshift 3.x?  It looks like it is still using 2.x.

**Comment by techniq** [comment]
Sure. I'd really like to finish the rewrite to drop react-virtualize so
it's all part of the next major semver.

**Comment by shilangyu** [comment]
Downshift 2.x method did work for mui-downshift v1.4.1
Thank you for your help
