### ISSUE TITLE
Migrate to Material UI v4

### ISSUE THREAD

**Issue by Verbon** [techniq/mui-downshift#85]
Hi,

Material UI v4 has come out a few months ago (https://medium.com/material-ui/material-ui-v4-is-out-4b7587d1e701).
So, please migrate mui-downshift to support Material UI v4.
Currently the following warning is displayed in console when installing a package:

```
warning "... > mui-downshift@1.4.1" has incorrect peer dependency "@material-ui/core@^3.0.0".
warning "... > mui-downshift@1.4.1" has incorrect peer dependency "@material-ui/icons@^3.0.0".
```

Here you can find the migration guide - https://material-ui.com/guides/migration-v3.

**Comment by techniq** [comment]
See: https://github.com/techniq/mui-downshift/pull/80 and https://github.com/techniq/mui-downshift/pull/83.

I currently don't have the time to do the work myself, and await a PR that does not have errors / regressions.   #83 was getting close but still had some [errors](https://github.com/techniq/mui-downshift/pull/80#issuecomment-515292950).  Most of the discussion was taking place in #80 but the best PR is #83.
